### ISSUE TITLE
No matching distribution found for sqlite-devel

### ISSUE THREAD

**Issue by maxiceptr** [lebinh/ngxtop#60]
I run the that command via ssh 
yum -y install python-pip; pip install ngxtop sqlite-devel

And it says:

Installed:
python-pip.noarch 0:7.1.0-1.el7                                                                                                                          
Complete!
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting ngxtop
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading ngxtop-0.0.2-py2.py3-none-any.whl
Collecting sqlite-devel
Could not find a version that satisfies the requirement sqlite-devel (from versions: )
No matching distribution found for sqlite-devel

I think, a sqlite-devel problem. 

P.S: Operation system is centos 7 64bit

**Comment by richarson** [comment]
Shoudn't that command line be:

```
yum -y install python-pip sqlite-devel
pip install ngxtop
```
?

**Comment by maxiceptr** [comment]
Ah okay problem is fixed thank you so much.
