### ISSUE TITLE
Any way to filter the request_path ? 

### ISSUE THREAD

**Issue by maxiceptr** [lebinh/ngxtop#61]
Hello

Is possible that any way to filter the request_path? For example I want to see analyze the just ".css" files (hit count /4xx 3xx 2xx errors)

Are there any parameter ?

**Comment by sandeep06011991** [comment]
Can I be assigned this feature

**Comment by lebinh** [comment]
@maxiceptr hi there, sorry for this late reply but you can use `--filter` param for this, e.g. `ngxtop --filter 'request_path.endswith(".css")'`
