### ISSUE TITLE
ngxtop no data gathering from access log

### ISSUE THREAD

**Issue by kimjangnam** [lebinh/ngxtop#73]
Can you help me what problem is?
no data summary from access log

# ngxtop
running for 42 seconds, 0 records processed: 0.00 req/sec

Summary:
|   count | avg_bytes_sent   |   2xx |   3xx |   4xx |   5xx |
|---------+------------------+-------+-------+-------+-------|
|	0 ||     0 |     0 |     0 |     0 |

Detailed:
| request_path   | count   | avg_bytes_sent   | 2xx   | 3xx   | 4xx   | 5xx   |
|----------------+---------+------------------+-------+-------+-------+-------|246

**Comment by lebinh** [comment]
Hi @kimjangnam , looks like it guessed the location of your access logs incorrectly, thus couldn't get any records. Would you mind sharing your nginx config so I can take a look?

**Comment by Maple-Ro** [comment]
same to me, and here is my http config part of nginx.conf file 
![image](https://user-images.githubusercontent.com/16970224/40034609-45708746-5830-11e8-8e18-198bb3b7e968.png)

**Comment by Maple-Ro** [comment]
@lebinh
