### ISSUE TITLE
parsing other log-files

### ISSUE THREAD

**Issue by belaoulidris** [lebinh/ngxtop#81]
Hi 

is there a way to parse other log files other then access.log, for example app.access.log ?

**Comment by dfmcvn** [comment]
ngxtop -l /path/to/app.access.log ?

**Comment by belaoulidris** [comment]
I have tried that @dfmcvn . it didn't work.
![no-logs](https://user-images.githubusercontent.com/7899551/32942692-15dc4fde-cb8a-11e7-86fa-f60aa724b2b2.png)

**Comment by dfmcvn** [comment]
https://imgur.com/oPtwmaL
Tried that, work well. Maybe the problemd is in your log file?

**Comment by joshnabbott** [comment]
@belaoulidris  This was happening to me too and my nginx config is using a custom log format, which turned out to be the issue. Check your nginx.conf file to see if you're doing the same (grep for `log_format` in the config directory) and if so, just pass `ngxtop` the config format and it works:

```
ngxtop -f '$remote_addr - $remote_user [$time_iso8601] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" "$host"' -l /path/to/access.log
```

**Comment by belaoulidris** [comment]
> @belaoulidris This was happening to me too and my nginx config is using a custom log format, which turned out to be the issue. Check your nginx.conf file to see if you're doing the same (grep for `log_format` in the config directory) and if so, just pass `ngxtop` the config format and it works:
> 
> ```
> ngxtop -f '$remote_addr - $remote_user [$time_iso8601] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" "$host"' -l /path/to/access.log
> ```

Thanks, @joshnabbott that works now, indeed it was a custom log file and I had to pass the log format to get it to work.
