### ISSUE TITLE
Selection of the actual fork of this project (lebinh/ngxtop)

### ISSUE THREAD

**Issue by click0** [lebinh/ngxtop#96]
Due to inactivity of maintainer (@lebinh) of this project (lebinh/ngxtop) I'm looking for a more efficient fork ngxtop.

**Comment by darthdeus** [comment]
Have you amnaged to find one?

**Comment by click0** [comment]
Not found. Yes, and lost interest in the project.

**Comment by oxr463** [comment]
Try this: https://github.com/ngxtop/ngxtop

@click0 please don't give up!

**Comment by lebinh** [comment]
Thanks, and just in case you still remember what made you looking for "a more efficient", please let me know in another issue.
