### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by matt-matt1** [lebinh/ngxtop#99]
Hi

$ ngxtop info
Traceback (most recent call last):
  File "/usr/local/bin/ngxtop", line 6, in <module>
    from ngxtop.ngxtop import main
  File "/usr/local/lib/python3.6/dist-packages/ngxtop/ngxtop.py", line 77, in <module>
    from config_parser import detect_log_config, detect_config_path, extract_variables, build_pattern
ModuleNotFoundError: No module named 'config_parser'

What's wrong/missing?

**Comment by dradux** [comment]
This is a python 3.x issue, see here for more info and solution: https://github.com/lebinh/ngxtop/issues/49

**Comment by lebinh** [comment]
Latest package from PyPi should fix this already.
